services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pnscore
    volumes:
      - postgres_data:/var/lib/postgresql/18/data
    restart: unless-stopped

volumes:
  postgres_data:
